---
title: "Data Base Key"
author: "Erlend B. Nilsen"
date: "06.11.2019"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
knit: (function(input_file, encoding) {
  out_dir <- "docs";
  rmarkdown::render(input_file,encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'databasekey.html'))})
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction
This document describe and document the tables in the database **Lierne_WP_Project_Data.db**. In addition, a short intro to how to enter data through software R and how to access data from R is given. The data base is a SQLite database. More information about SQLite can be found here (ref).

### Data ownership and provenance
This database contain data from the willow ptarmigan project in Lierne. The project was initiated in 2015, in collaboration between NINA and Nord University. Data provenance and ownership is dictated by the contracts, and might to some extent vary between the different data sets. As long as data are kept "in house" this is solved by agreements between the project leaders at NINA and Nord University, respectively. When data are published and publicly available, they will be so following the FAIR principles for data publication. This means that they will be accompanied by both a CC licence and a citation string. 

### Data sources
The core of the project, and this data set, is data collected from radio collared willow ptarmigan in Lierne municipality. Following the project research plan, ca. 40 willow ptarmigans are captured and instrumented with VHF neck collars each winter (February-March). At capture, various morphological and physiologial measures are recorded. The birds are monitored until mortality is recorded or until we loose contact (e.g. due to collar failure or movement out of the study area). During the breeding season, the breeding success of marked females are monitored using game cameras/camera traps at the nest. 

In addition to the main field data collection described above, we conduct various short- and long term projects that are not based on marked individuals. These projects include ..

## Data base tables
Currently there are seven tables associated with the data gathered from 2015 until present. These are separated into two categories: tables that contain information regarding the marked willow ptarmigans themselves and tables that contain information about the nest. Table nomenclature follow the structure of "Marked_XX.." and "NestMonitor_XX.." for marked birds tables and nest tables respectively.

All "Marked_XX" tables contain the following columns: "OccurrenceID", "OrganismID", "RingNR", "Date", "Comment", "Observer1", "Observer2" and "JulianDate". "OccurrenceID" and "OrganismID" are uniquely generated identification codes, and "RingNR" is the leg band number given to the marked birds upon capture. The rest are self-explanatory and require no further description.

Similarly to the "Marked_XX" tables, all "NestMonitor_XX" tables have columns describing "NestUUID", "organismID", "Comments" and "RingNR". All "NestMonitor_XX" tables also have "Year", "NestName" and "Nestname1". "NestUUID" and "organismsID" are unique identification codes. "NestName" is the "Year" variable appended to the "RingNR" variable, while "NestName1" is identical to the "RingNR" variable for all willow ptarmigan that have a "RingNR". For willow ptarmigan without a "RingNR" (Observer happened to come across a willow ptarmigan nest and mounted a wildlife camera there) "NestName" is a unique code with "Year" appended (e.g., "2015U01_2015", "2015U02_2015", "..."), while "NestName1" is just the unique code (e.g., "2015U01", "2015U02", "..."). 

### Capture details
**Marked_CaptureDetails**. Contains all measurements conducted during the capture and marking of willow ptarmigan: Age at capture (CaptureAge, juv/ad), estimated sex (Sex_fieldbased), sex based on DNA analysis (Sex_dna), weight at capture (Weight), sternum length (Chest), wing lengths (LeftWing, RightWing, left and right), the breathing frequency at capture (BreadingFreq), the activity level at capture (Boldness, active/calm) and the gizzard fill (0, 0.25, 0.5, 0.75, 1). The final column details if the captured bird has been recaptured (1 = not recaptured, 2 = recaptured) or not (Recapture).

### Collar information
**Marked_CollarInfo**. The information regarding the radio transmitters themselves is stored here. The unique collar number (CollarNR), its radio frequency on the 152Mhz band (CollarFrequency), the radio spectrum of the transmitter (CollarType, VHF), if the collar has been discarded or not (CollarDiscarded), and the production year of the radio transmitter (CollarProdYear).   

### Occurences
**Marked_Occurences**. This table contains all occurrences of willow ptarmigan in the study (including death occurrences). The status (Status) of the occurrence is given first:  
  1 = Capture event  
  2 = Alive  
  3-6 & 8 see below  
  7 = Searched for but not heard  
    
The position of the occurrence in the Universal Transverse Mercator coordinate system (UTM_X, UTM_Y), zone 33 (Zone) and the accuracy of the position (PosAccuracy) is then given:  
  1 = Precise position  
  2 = Coarse position  
  3 = Aerial position  
  4 = Signal heard but without any accuracy in position (i.e., only used omni-antenna, very conflicting bearings, single telemetry bearing)   

### Mortality details
**Marked_DeathDetails**. The table that contain all mortality occurrences. The death status is described first (Status):  
  3 = Dead by harvest  
  4 = Dead by predation  
  5 = Dead unknown  
  6 = Transmitting mortality  
  8 = Capture-related mortality.  
    
The cause of death (CauseOfDeath) is then described:  
  Shot, mammal, raptor, red fox, goldeneagle, crippling mortality or unknown.


### Nest demography
**NestMonitor_Demography**. Contains columns for the observer(s) that mounted the game camera at a nest and the observer(s) that retrieved said camera. Further, there is information regarding the female and the nest itself: If the female was on the nest when flushed (FemaleOnNest, yes/no), if the female was on the nest during set up of the game camera (OnNest_SetUp, yes/no), the distance from the observer to the female when flushed (FlushDistance, in meters), if the male was observed when the female was flushed (MaleObs, yes/no), the number of eggs in the nest (N_egg), the number of eggs hatched (N_egg_hatched) and unhatched (N_egg_unhatched), the state of the nest (Nest_Status, hatched, predated, abandoned...), the date the eggs were hatched, abandoned or predated (Date_nest_Status), the type of predator that predated the nest (Nest_predator, no, redfox, goldeneagle, ...) and the state of the female at the time of the nest event (Female_state_nestEvent, unknown, dead_unknown, dead_predation or alive). 

### Nest metadata
**NestMonitor_Metadata**. The table contains the date for the set up of the game cameras (CameraSetupDate), retrieval (CameraRetrievalDate), the ID of the camera (CameraID) and memory card (MemoryID), the position of the game camera (Zone, UTM_X, and UTM_Y), the observer(s) for set up (Observer1_SetUp, Observer2_SetUp) and retrieval (Observer1_Retrieval, Observer2_Retrieval), as well as the municipality (Municipality, Lierne, Snåsa, Grong, or Røyrvik) and location (Location) of the game camera.

### Nest picture list
**NestMonitoring_PictureList**. A table containing a list of all the game camera pictures taken during the study. The date (Date), time (Time), and year (Year) of each picture, as well as the name of the file (FileName), the old name of the file (OldFileName), if the date is readable (DateReadable), the directory of the stored file (outDir) and the copy status of the file (CopyStatus).






